export type ThemeId = "mono" | "cyber" | "forest" | "amber" | "slate" | "rose" | "violet" | "arctic";

export interface PortfolioStyle {
  id: ThemeId;
  name: string;
  emoji: string;
  vibe: string;
  swatches: string[];
  vars: Record<string, string>;
}

export const PORTFOLIO_STYLES: PortfolioStyle[] = [
  {
    id: "mono",
    name: "Mono",
    emoji: "◆",
    vibe: "Zero decoration. Razor edges. Pure content.",
    swatches: ["#0a0a0a", "#ffffff", "#333333"],
    vars: {
      "--pt-bg":               "#0a0a0a",
      "--pt-bg2":              "#111111",
      "--pt-bg3":              "#161616",
      "--pt-fg":               "#ffffff",
      "--pt-fg2":              "#cccccc",
      "--pt-fg3":              "#666666",
      "--pt-accent":           "#ffffff",
      "--pt-accent-fg":        "#000000",
      "--pt-border":           "#222222",
      "--pt-border2":          "#333333",
      "--pt-tag-bg":           "#111111",
      "--pt-tag-fg":           "#888888",
      "--pt-tag-border":       "#222222",
      "--pt-btn-bg":           "#ffffff",
      "--pt-btn-fg":           "#000000",
      "--pt-radius":           "0px",
      "--pt-radius-photo":     "0px",
      "--pt-btn-radius":       "0px",
      "--pt-card-pad":         "1.25rem",
      "--pt-card-border":      "1px solid #222222",
      "--pt-card-shadow":      "none",
      "--pt-heading-size":     "2.5rem",
      "--pt-heading-weight":   "900",
      "--pt-heading-tracking": "-0.02em",
      "--pt-section-gap":      "3rem",
      "--pt-nav-style":        "underline",
    },
  },
  {
    id: "cyber",
    name: "Cyber",
    emoji: "◈",
    vibe: "Neon glow. Pill shapes. Matrix energy.",
    swatches: ["#050510", "#00ffcc", "#1a1a2e"],
    vars: {
      "--pt-bg":               "#050510",
      "--pt-bg2":              "#0a0a1a",
      "--pt-bg3":              "#0f0f20",
      "--pt-fg":               "#e0ffe0",
      "--pt-fg2":              "#a0e0c0",
      "--pt-fg3":              "#406050",
      "--pt-accent":           "#00ffcc",
      "--pt-accent-fg":        "#000000",
      "--pt-border":           "#0a2a20",
      "--pt-border2":          "#0f3530",
      "--pt-tag-bg":           "#001a14",
      "--pt-tag-fg":           "#00cc99",
      "--pt-tag-border":       "#003322",
      "--pt-btn-bg":           "#00ffcc",
      "--pt-btn-fg":           "#000000",
      "--pt-radius":           "9999px",
      "--pt-radius-photo":     "9999px",
      "--pt-btn-radius":       "9999px",
      "--pt-card-pad":         "1.25rem",
      "--pt-card-border":      "1px solid #0a2a20",
      "--pt-card-shadow":      "0 0 20px rgba(0,255,204,0.05)",
      "--pt-heading-size":     "2.5rem",
      "--pt-heading-weight":   "900",
      "--pt-heading-tracking": "-0.02em",
      "--pt-section-gap":      "3rem",
      "--pt-nav-style":        "pill",
    },
  },
  {
    id: "forest",
    name: "Forest",
    emoji: "▲",
    vibe: "Chunky cards. Organic radius. Terminal green.",
    swatches: ["#0d1a0d", "#4ade80", "#1a2e1a"],
    vars: {
      "--pt-bg":               "#0d1a0d",
      "--pt-bg2":              "#111f11",
      "--pt-bg3":              "#162416",
      "--pt-fg":               "#e0ffe0",
      "--pt-fg2":              "#a0c8a0",
      "--pt-fg3":              "#4a7a4a",
      "--pt-accent":           "#4ade80",
      "--pt-accent-fg":        "#000000",
      "--pt-border":           "#1a3a1a",
      "--pt-border2":          "#254025",
      "--pt-tag-bg":           "#0f2a0f",
      "--pt-tag-fg":           "#3ab860",
      "--pt-tag-border":       "#1a3a1a",
      "--pt-btn-bg":           "#4ade80",
      "--pt-btn-fg":           "#000000",
      "--pt-radius":           "16px",
      "--pt-radius-photo":     "16px",
      "--pt-btn-radius":       "12px",
      "--pt-card-pad":         "1.5rem",
      "--pt-card-border":      "1px solid #1a3a1a",
      "--pt-card-shadow":      "0 4px 24px rgba(0,0,0,0.4)",
      "--pt-heading-size":     "2.5rem",
      "--pt-heading-weight":   "900",
      "--pt-heading-tracking": "-0.02em",
      "--pt-section-gap":      "3.5rem",
      "--pt-nav-style":        "solid",
    },
  },
  {
    id: "amber",
    name: "Amber",
    emoji: "◇",
    vibe: "Magazine layout. Massive type. Gallery air.",
    swatches: ["#0f0a00", "#f59e0b", "#1a1200"],
    vars: {
      "--pt-bg":               "#0f0a00",
      "--pt-bg2":              "#160f00",
      "--pt-bg3":              "#1c1400",
      "--pt-fg":               "#fff8e0",
      "--pt-fg2":              "#d4b860",
      "--pt-fg3":              "#7a6030",
      "--pt-accent":           "#f59e0b",
      "--pt-accent-fg":        "#000000",
      "--pt-border":           "#2a1e00",
      "--pt-border2":          "#3a2a00",
      "--pt-tag-bg":           "#1a1200",
      "--pt-tag-fg":           "#c47c00",
      "--pt-tag-border":       "#2a1e00",
      "--pt-btn-bg":           "#f59e0b",
      "--pt-btn-fg":           "#000000",
      "--pt-radius":           "2px",
      "--pt-radius-photo":     "2px",
      "--pt-btn-radius":       "2px",
      "--pt-card-pad":         "1.5rem",
      "--pt-card-border":      "1px solid #2a1e00",
      "--pt-card-shadow":      "none",
      "--pt-heading-size":     "3.5rem",
      "--pt-heading-weight":   "900",
      "--pt-heading-tracking": "-0.04em",
      "--pt-section-gap":      "4rem",
      "--pt-nav-style":        "underline",
    },
  },
  {
    id: "slate",
    name: "Slate",
    emoji: "⬡",
    vibe: "SaaS dashboard. Compact grid. No-nonsense.",
    swatches: ["#0f1117", "#6366f1", "#1a1d2e"],
    vars: {
      "--pt-bg":               "#0f1117",
      "--pt-bg2":              "#141720",
      "--pt-bg3":              "#1a1d28",
      "--pt-fg":               "#e2e8f0",
      "--pt-fg2":              "#94a3b8",
      "--pt-fg3":              "#475569",
      "--pt-accent":           "#6366f1",
      "--pt-accent-fg":        "#ffffff",
      "--pt-border":           "#1e2130",
      "--pt-border2":          "#2a2f45",
      "--pt-tag-bg":           "#1a1d28",
      "--pt-tag-fg":           "#6366f1",
      "--pt-tag-border":       "#2a2f45",
      "--pt-btn-bg":           "#6366f1",
      "--pt-btn-fg":           "#ffffff",
      "--pt-radius":           "6px",
      "--pt-radius-photo":     "6px",
      "--pt-btn-radius":       "6px",
      "--pt-card-pad":         "1rem",
      "--pt-card-border":      "1px solid #1e2130",
      "--pt-card-shadow":      "none",
      "--pt-heading-size":     "2rem",
      "--pt-heading-weight":   "700",
      "--pt-heading-tracking": "-0.01em",
      "--pt-section-gap":      "2.5rem",
      "--pt-nav-style":        "solid",
    },
  },
  {
    id: "rose",
    name: "Rose",
    emoji: "◻",
    vibe: "Full-bleed drama. Oversized title. Loud.",
    swatches: ["#0f0008", "#f43f5e", "#1a0010"],
    vars: {
      "--pt-bg":               "#0f0008",
      "--pt-bg2":              "#16000d",
      "--pt-bg3":              "#1c0012",
      "--pt-fg":               "#ffe4ec",
      "--pt-fg2":              "#f9a8c0",
      "--pt-fg3":              "#7a3050",
      "--pt-accent":           "#f43f5e",
      "--pt-accent-fg":        "#ffffff",
      "--pt-border":           "#2a0018",
      "--pt-border2":          "#3a0022",
      "--pt-tag-bg":           "#16000d",
      "--pt-tag-fg":           "#e11d48",
      "--pt-tag-border":       "#2a0018",
      "--pt-btn-bg":           "#f43f5e",
      "--pt-btn-fg":           "#ffffff",
      "--pt-radius":           "4px",
      "--pt-radius-photo":     "50%",
      "--pt-btn-radius":       "4px",
      "--pt-card-pad":         "1.5rem",
      "--pt-card-border":      "1px solid #2a0018",
      "--pt-card-shadow":      "4px 4px 0 #f43f5e22",
      "--pt-heading-size":     "4rem",
      "--pt-heading-weight":   "900",
      "--pt-heading-tracking": "-0.04em",
      "--pt-section-gap":      "4rem",
      "--pt-nav-style":        "underline",
    },
  },
  {
    id: "violet",
    name: "Violet",
    emoji: "◆",
    vibe: "Left-border accents. Rich purple. DeFi.",
    swatches: ["#0a0514", "#7c3aed", "#140a28"],
    vars: {
      "--pt-bg":               "#0a0514",
      "--pt-bg2":              "#0f081c",
      "--pt-bg3":              "#140a24",
      "--pt-fg":               "#ede9fe",
      "--pt-fg2":              "#c4b5fd",
      "--pt-fg3":              "#6d28a0",
      "--pt-accent":           "#7c3aed",
      "--pt-accent-fg":        "#ffffff",
      "--pt-border":           "#1e1040",
      "--pt-border2":          "#2a1850",
      "--pt-tag-bg":           "#110730",
      "--pt-tag-fg":           "#8b5cf6",
      "--pt-tag-border":       "#1e1040",
      "--pt-btn-bg":           "#7c3aed",
      "--pt-btn-fg":           "#ffffff",
      "--pt-radius":           "8px",
      "--pt-radius-photo":     "8px",
      "--pt-btn-radius":       "8px",
      "--pt-card-pad":         "1.25rem",
      "--pt-card-border":      "1px solid #1e1040",
      "--pt-card-shadow":      "none",
      "--pt-heading-size":     "2.5rem",
      "--pt-heading-weight":   "800",
      "--pt-heading-tracking": "-0.02em",
      "--pt-section-gap":      "3rem",
      "--pt-nav-style":        "pill",
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    emoji: "◇",
    vibe: "Light mode. Newspaper grid. Maximum air.",
    swatches: ["#f8fafc", "#0f172a", "#e2e8f0"],
    vars: {
      "--pt-bg":               "#f8fafc",
      "--pt-bg2":              "#f1f5f9",
      "--pt-bg3":              "#e2e8f0",
      "--pt-fg":               "#0f172a",
      "--pt-fg2":              "#334155",
      "--pt-fg3":              "#94a3b8",
      "--pt-accent":           "#0f172a",
      "--pt-accent-fg":        "#f8fafc",
      "--pt-border":           "#cbd5e1",
      "--pt-border2":          "#94a3b8",
      "--pt-tag-bg":           "#e2e8f0",
      "--pt-tag-fg":           "#475569",
      "--pt-tag-border":       "#cbd5e1",
      "--pt-btn-bg":           "#0f172a",
      "--pt-btn-fg":           "#f8fafc",
      "--pt-radius":           "0px",
      "--pt-radius-photo":     "0px",
      "--pt-btn-radius":       "0px",
      "--pt-card-pad":         "1.5rem",
      "--pt-card-border":      "2px solid #0f172a",
      "--pt-card-shadow":      "none",
      "--pt-heading-size":     "2.5rem",
      "--pt-heading-weight":   "900",
      "--pt-heading-tracking": "-0.02em",
      "--pt-section-gap":      "4.5rem",
      "--pt-nav-style":        "underline",
    },
  },
];

export function applyStyle(id: ThemeId) {
  const style = PORTFOLIO_STYLES.find((s) => s.id === id) ?? PORTFOLIO_STYLES[0];
  const root = document.documentElement;
  Object.entries(style.vars).forEach(([key, val]) => {
    root.style.setProperty(key, val);
  });
  try { localStorage.setItem("portfolio_theme", id); } catch {}
}
